"""Render results/* into docs/RESULTS_TABLES.md (numbers only; interpretation lives in REPORT.md)."""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from vrp_ltr import registry  # noqa: E402

PAPER = {"EA": (3.1048, 5.7612), "FMU": (2.5119, 5.0632), "SRS": (2.7597, 5.2622), "VT": (2.2102, 4.6669),
         "GB": (2.0554, 5.0147), "HK": (1.9464, 4.3711), "QK": (1.8965, 4.3084)}
PAPER_YEAR_EA = {"2021": 6.5184, "2022": 2.5066, "2023": 1.7852, "2024": 0.4074}


def fmt(x, nd=2):
    if x is None or (isinstance(x, float) and not np.isfinite(x)):
        return "—"
    return f"{x:,.{nd}f}" if isinstance(x, (int, float, np.floating)) else str(x)


def md(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    out = ["| " + " | ".join(map(str, cols)) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows():
        out.append("| " + " | ".join(fmt(v) if not isinstance(v, str) else v for v in r.values) + " |")
    return "\n".join(out)


def main():
    lines = ["# RESULTS_TABLES (auto-generated by scripts/summarize.py)", "",
             f"Trials recorded in registry (DSR N): **{registry.n_trials()}**", ""]
    for pol in ("P-LAG", "A-LAG"):
        base = ROOT / "results" / pol
        if not base.exists():
            continue
        lines += [f"## Policy {pol}", ""]
        # window meta
        rows = []
        for w in ("WF1", "WF2", "WF3", "WF4", "OOT", "EXT_B"):
            f = base / w / "meta.json"
            if f.exists():
                m = json.loads(f.read_text())
                rows.append({"window": w, "n_train_days": m["n_train_days"], "features_S1..S5": str(m["selection"]),
                             "SKIP_in_grade1": str(m["skip_in_grade1"]), "gate_tau": m["gate"]["tau"],
                             "gate_rate": m["gate"]["rate"], "search_ndcg1": m["tuning"]["best_ndcg1_search"]})
        if rows:
            lines += ["### Windows", md(pd.DataFrame(rows)), ""]
        for g in ("G-UNION", "G-LAST6"):
            for ext in ("A", "B"):
                f = base / f"one_contract_{g}_ext{ext}.csv"
                if not f.exists():
                    continue
                R = pd.read_csv(f)
                lines += [f"### One-contract SPXW — gate {g}, 2026 Test {ext}", ""]
                for lvl in ("L1", "L2", "L3", "L3_1003", "DOUBLE"):
                    t = R[R["level"] == lvl].pivot_table(index="strategy", columns="slice", values="sharpe_arith_daily_pnl")
                    tp = R[R["level"] == lvl].pivot_table(index="strategy", columns="slice", values="total_pnl")
                    if len(t):
                        lines += [f"**Sharpe (daily $ P&L, arithmetic, ×√252) — {lvl}**", "",
                                  md(t.reset_index().round(2)), "", f"**Net P&L $ per 1 contract — {lvl}**", "",
                                  md(tp.reset_index().round(0)), ""]
                sa = base / f"selection_alpha_{g}_ext{ext}.json"
                if sa.exists():
                    lines += ["**Selection-alpha verdict (M-HEAD − B-FIX-BESTTRAIN)**", "", "```",
                              sa.read_text()[:2000], "```", ""]
        f = base / "paper_sizing_G-UNION.json"
        if f.exists():
            S = json.loads(f.read_text())
            rows = []
            for m, d in S.items():
                rows.append({"method": m, "paper_WF": PAPER.get(m, (None, None))[0], "ours_WF_geom": d.get("WF", {}).get("sharpe_geom"),
                             "paper_OOT": PAPER.get(m, (None, None))[1], "ours_OOT_geom": d.get("OOT_2025", {}).get("sharpe_geom"),
                             **{f"ours_{y}": d.get(y, {}).get("sharpe_geom") for y in ("2021", "2022", "2023", "2024")},
                             "ours_WF_maxdd": d.get("WF", {}).get("max_dd"), "ours_OOT_maxdd": d.get("OOT_2025", {}).get("max_dd")})
            lines += ["### Paper sizing replication ($5M, equal-vol θ)", md(pd.DataFrame(rows)), "",
                      f"Paper EA per-year: {PAPER_YEAR_EA}", ""]
        for root in ("XSP", "SPY"):
            f = base / f"25k_{root}_G-UNION.json"
            if not f.exists():
                continue
            J = json.loads(f.read_text())
            rows = []
            for k, v in J["results"].items():
                a = v.get("ALL_2021_2026", {})
                rows.append({"variant": k, "trades": a.get("trades"), "net_pnl": a.get("net_pnl"),
                             "sharpe_all": a.get("sharpe_arith"), "WF": v.get("WF_2021_2024", {}).get("sharpe_arith"),
                             **{y: v.get(y, {}).get("sharpe_arith") for y in ("2021", "2022", "2023", "2024", "2025", "2026")},
                             "maxdd": a.get("max_dd"), "worst_day": a.get("worst_day"),
                             "minus_best5": a.get("minus_best5"), "boot_p": a.get("boot_p_gt0")})
            lines += [f"### $25k {root} (NAV0 $25,000, 1 lot)", md(pd.DataFrame(rows)), "",
                      "**Primary evaluation**", "```", json.dumps(J["primary_eval"], indent=1)[:3000], "```", ""]
    (ROOT / "docs" / "RESULTS_TABLES.md").write_text("\n".join(lines))
    print("\n".join(lines)[:6000])


if __name__ == "__main__":
    main()
